KamaTechOrg/KT_Cloud

Storage/Scripts/PyStorage.py
Storage/Scripts/metadata.py
Storage/Scripts/tests/test_get_object_attributes.py
Storage/Scripts/tests/test_get_object_tagging.py
Storage/Scripts/tests/test_put_object_tagging.py

Strgmng kan 76 naive implementation of aws s3 api functions

---

DB/Scripts/DBSecurityGroup.py
DB/Scripts/DBSubnetGroup.py
DB/Scripts/Gili_Bolak_Functions.py
DB/Scripts/OptionGroup.py

Dbmng kan111 naive implementation of aws rds api's functions

---

Storage/Controller/PolicyController.py
Storage/DataAccess/ObjectManager.py
Storage/DataAccess/StorageManager.py
Storage/Models/PolicyModel.py
Storage/Service/Abc/STO.py
Storage/Service/Abc/STOE.py
Storage/Service/Classes/LogFiles.py
Storage/Service/Classes/PartService.py
Storage/Service/Classes/PolicyService.py
Storage/Test/Controller/PolicyController.py
Storage/Test/DataAccess/ObjectManager.py
Storage/Test/DataAccess/StorageManager.py
Storage/Test/Models/PolicyModel.py
Storage/Test/Service/Abc/STO.py
Storage/Test/Service/Abc/STOE.py
Storage/Test/Service/Classes/LogFiles.py
Storage/Test/Service/Classes/PartService.py
Storage/Test/Service/Classes/PolicyService.py
Storage/Test/TestService/SnapshotTest/DBClusterSnapshotTest.py
Storage/Test/TestService/SnapshotTest/DBSnapshotTest.py
Storage/Test/TestService/TestPolicy.py
Storage/Test/Validation/Validation.py
Storage/Validation/Validation.py

storage first commit

---

DB/Controller/DBSecurityGroupController.py
DB/Models/DBSecurityGroupModel.py
DB/Service/Classes/DBSecurityGroupService.py

basic infrastructure for db_security_group

basic infrastructure for db_security_group

---

DB/Controller/GlobalClusterController.py
DB/Service/Classes/Filter.py
DB/Service/Classes/GlobalClusterService.py
DB/configuration/filter_config.json

a helper object for data requests

filter object added

---

DB/Controller/DBSubnetGroupController.py
DB/Models/DBSubnetGroupModel.py
DB/Service/Classes/DBSubnetGroupService.py

basic infrastructure DBSubnetGroup

basic infrastructure DBSubnetGroup

---

Storage/DataAccess/StorageManager.py

@riki7649255 
this is the storagemanager file
I need your CR to merge it to the main
thank you

Write storage manager

---

Storage/DataAccess/VersionManager.py
Storage/Models/ObjectModel.py
Storage/Models/VesionModel.py
Storage/Service/Classes/VersionService.py

I add the model, the service and the dataAccess

adding the version class

---

Storage/DataAccess/VersionManager.py
Storage/Models/VesionModel.py

fix the prev PR

---

Storage/DataAccess/ObjectManager.py
Storage/Service/Classes/ObjectService.py

Declaration of naive functions
@riki7649255

Update ObjectManager naive implementation.py

---

Storage/Controller/PolicyController.py
Storage/Controller/PolicyControllerOld.py
Storage/DataAccess/policyManager.py
Storage/Models/PolicyModel.py
Storage/Models/PolicyModelOld.py
Storage/Service/Classes/PolicyService.py
Storage/Service/Classes/PolicyServiceOld.py

we add a new class policy
by Michal Quitt & Malki Marxon

Add class policy

---

Storage_UserAdministration/Controllers/PolicyController.py
Storage_UserAdministration/DataAccess/policyManager.py
Storage_UserAdministration/Models/PolicyModel.py
Storage_UserAdministration/Services/PolicyService.py

Finish the policy

---

Storage_UserAdministration/Controllers/PolicyController.py
Storage_UserAdministration/DataAccess/policyManager.py
Storage_UserAdministration/ML/LRUCache.py
Storage_UserAdministration/Models/PolicyModel.py
Storage_UserAdministration/Services/PolicyService.py

Add cache to policy

---

Storage_UserAdministration/Controllers/PolicyController.py
Storage_UserAdministration/DataAccess/policyManager.py
Storage_UserAdministration/Models/PolicyModel.py
Storage_UserAdministration/Services/PolicyService.py

add user to policy
by Malki & Michal

Add user to policy

---

Storage_UserAdministration/Controllers/PolicyController.py
Storage_UserAdministration/DataAccess/policyManager.py
Storage_UserAdministration/Services/PolicyService.py

delete user from policy
by Malki & Michal

Delete user from policy

---

Storage_UserAdministration/Controllers/PolicyController.py
Storage_UserAdministration/DataAccess/policyManager.py
Storage_UserAdministration/Services/PolicyService.py

Add generic function to add entity for policy

Add generic function to add entity for policy

---

Storage/Storage_ML/LRUCache.py
Storage/Storage_UserAdministration/Controllers/PolicyController.py
Storage/Storage_UserAdministration/DataAccess/policyManager.py
Storage/Storage_UserAdministration/Models/PolicyModel.py
Storage/Storage_UserAdministration/Services/PolicyService.py

change the pass for all policy

Change pass for policy

---

Storage/ETLS/CustomerPurchaseFrequencyTotalSpendWeeklyETL.py
Storage/ETLS/topSellingArtistsWeeklyETL.py

I wrote 2 ETL scripts
for customer table.
@riki7649255

Write ETL script

---

Storage/ELTS/CustomerPurchaseFrequencyTotalSpendWeeklyELT.py
Storage/ETLS/CustomerPurchaseFrequencyTotalSpendDailyETL.py

Add first script

---

Storage/Orchestration/ELTWeeklyProcess.py
Storage/Orchestration/ETLDailyProcess.py
Storage/Orchestration/ETLWeeklyProcess.py

I Orchestrate my ETL and ELT scripts.

Orchestrate ETL and ELT scripts

---

Storage/Orchestration/ELTWeeklyProcess.py
Storage/Orchestration/ETLDailyProcess.py
Storage/Orchestration/ETLWeeklyProcess.py

Orchetstrate ELT & ETL incremental daily

Orchestrate

---

DB/NEW_KT_DB/DataAccess/ObjectManager.py

I Add function to ObjectManager in Db
@riki7649255

Add function to ObjectManager in Db

---

Storage/NEW_KT_Storage/Controller/BucketController.py
Storage/NEW_KT_Storage/DataAccess/BucketManager.py
Storage/NEW_KT_Storage/Models/BucketModel.py
Storage/NEW_KT_Storage/Service/Classes/BucketService.py
Storage/NEW_KT_Storage/Test/BucketTest.py
Storage/NEW_KT_Storage/Validation/BucketValidations.py

I wrote functions that work:
Creation, retrieval, deletion
and a validation file and a test file
@riki7649255

Write & run bucket

---

Storage/NEW_KT_Storage/Controller/BucketController.py
Storage/NEW_KT_Storage/DataAccess/BucketManager.py
Storage/NEW_KT_Storage/Exceptions/BucketExceptions.py
Storage/NEW_KT_Storage/Models/BucketModel.py
Storage/NEW_KT_Storage/Service/Classes/BucketService.py
Storage/NEW_KT_Storage/Test/BucketTest.py
Storage/NEW_KT_Storage/Validation/BucketValidations.py

I wrote more tests and added error typing
(There are changes in this code because of the tests..)
@riki7649255

Write more test & use my exeption

---

Storage/NEW_KT_Storage/Controller/BucketController.py
Storage/NEW_KT_Storage/Integration/BucketIntegration.py
Storage/NEW_KT_Storage/Service/Classes/BucketService.py

Hei
I wrote the bucket integration
@riki7649255

Write bucket Integration

---

Storage/NEW_KT_Storage/Controller/BucketController.py
Storage/NEW_KT_Storage/DataAccess/BucketManager.py
Storage/NEW_KT_Storage/Exceptions/BucketExceptions.py
Storage/NEW_KT_Storage/Integration/BucketIntegration.py
Storage/NEW_KT_Storage/Models/BucketModel.py
Storage/NEW_KT_Storage/Service/Classes/BucketService.py
Storage/NEW_KT_Storage/Test/BucketTest.py
Storage/NEW_KT_Storage/Validation/BucketValidations.py

Hei @riki7649255 
I Add lines & remove lines to the code

Add lines & remove lines

---

DB/NEW_KT_DB/DataAccess/DBManager.py

Deleting an unnecessary return
